Added a script to display file permissions in octal format

diff --git a/scripts/perms b/scripts/perms
--- a/scripts/perms
+++ b/scripts/perms
@@ -7,3 +7,16 @@
 # 775 weather
 # 664 ../README.md
 
+if [$# -eq 0];then
+    echo "Usage: $0 file1 [file2 ...]"
+    exit 1
+fi
+for file in "$@";do
+    if [ -e "$file" ];then
+        perms=$(stat -c "%a" "$file")
+        echo "$perms $file"
+    else
+        echo "Error"
+    fi
+done
+
